# Generated by Django 5.2.11 on 2026-02-18 20:13

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('WAREHOUSE', 'Warehouse'), ('THREEPL', '3PL'), ('IN_TRANSIT', 'In Transit')], default='WAREHOUSE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('IN_TRANSIT', 'In Transit'), ('PARTIALLY_RECEIVED', 'Partially Received'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=24)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(blank=True, max_length=100, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PICKED_UP', 'Picked Up'), ('IN_TRANSIT', 'In Transit'), ('ARRIVED', 'Arrived'), ('DELIVERED', 'Delivered')], default='CREATED', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.location')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='core.purchaseorder')),
                ('from_supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.supplier')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.shipment')),
            ],
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.supplier'),
        ),
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('SHOPIFY', 'Shopify'), ('AMAZON', 'Amazon')], max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='RUNNING', max_length=20)),
                ('detail', models.TextField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='supplier',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('uom', models.CharField(default='each', max_length=32)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'sku')},
            },
        ),
        migrations.AddField(
            model_name='location',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('PO_RECEIPT', 'PO Receipt'), ('SALE', 'Sale'), ('ADJUSTMENT', 'Adjustment'), ('TRANSFER', 'Transfer')], max_length=20)),
                ('qty_delta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ref_type', models.CharField(max_length=50)),
                ('ref_id', models.CharField(max_length=100)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('SHOPIFY', 'Shopify'), ('AMAZON', 'Amazon')], max_length=20)),
                ('sku', models.CharField(max_length=64)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('as_of', models.DateTimeField(default=django.utils.timezone.now)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('SHOPIFY', 'Shopify'), ('AMAZON', 'Amazon')], max_length=20)),
                ('name', models.CharField(default='default', max_length=100)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('shop_domain', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('received_qty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.purchaseorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product')),
            ],
            options={
                'unique_together': {('po', 'product')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='purchaseorder',
            unique_together={('tenant', 'po_number')},
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('tenant', 'name')},
        ),
        migrations.CreateModel(
            name='InventoryBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_hand', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('reserved', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'product', 'location')},
            },
        ),
        migrations.CreateModel(
            name='ChannelOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('SHOPIFY', 'Shopify'), ('AMAZON', 'Amazon')], max_length=20)),
                ('external_order_id', models.CharField(max_length=100)),
                ('processed_at', models.DateTimeField()),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'channel', 'external_order_id')},
            },
        ),
    ]
