# Generated by Django 5.2.11 on 2026-02-21 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tenant_currency_code_salesorder_salesorderline'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='purchaseorderline',
            unique_together=set(),
        ),
    ]
