# Generated by ChatGPT on 2026-02-21

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_purchaseorderline_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnitOfMeasure",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=32)),
                ("name", models.CharField(blank=True, max_length=64, null=True)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.tenant")),
            ],
            options={
                "unique_together": {("tenant", "code")},
            },
        ),
        migrations.AddField(
            model_name="product",
            name="parent",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="variants", to="core.product"),
        ),
        migrations.AddField(
            model_name="product",
            name="variant_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="option1",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="option2",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="option3",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="base_uom",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="core.unitofmeasure"),
        ),
        migrations.AddField(
            model_name="product",
            name="cost_method",
            field=models.CharField(choices=[("FIFO", "FIFO"), ("AVERAGE", "Average"), ("STANDARD", "Standard")], default="AVERAGE", max_length=20),
        ),
        migrations.AddField(
            model_name="product",
            name="standard_cost",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
        ),
        migrations.CreateModel(
            name="ProductBarcode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=64)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="barcodes", to="core.product")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.tenant")),
            ],
            options={
                "unique_together": {("tenant", "code")},
            },
        ),
        migrations.CreateModel(
            name="UOMConversion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("multiplier", models.DecimalField(decimal_places=6, help_text="Multiply qty in from_uom by this to get qty in to_uom.", max_digits=18)),
                ("from_uom", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="conversions_from", to="core.unitofmeasure")),
                ("to_uom", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="conversions_to", to="core.unitofmeasure")),
                ("product", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="uom_conversions", to="core.product")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.tenant")),
            ],
            options={
                "unique_together": {("tenant", "product", "from_uom", "to_uom")},
            },
        ),
        migrations.CreateModel(
            name="BillOfMaterials",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(default="Default BOM", max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="boms", to="core.product")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.tenant")),
            ],
            options={
                "unique_together": {("tenant", "product", "name")},
            },
        ),
        migrations.CreateModel(
            name="BillOfMaterialsLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("qty", models.DecimalField(decimal_places=2, max_digits=12)),
                ("bom", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="core.billofmaterials")),
                ("component", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="bom_component_of", to="core.product")),
                ("uom", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="core.unitofmeasure")),
            ],
            options={
                "unique_together": {("bom", "component")},
            },
        ),
    ]
