
# Generated by ChatGPT on 2026-02-21

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_masterdata_variants_uom_bom"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorymovement",
            name="lot_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="inventorymovement",
            name="serial_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="inventorymovement",
            name="expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="InventoryLotBalance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("lot_code", models.CharField(blank=True, max_length=50, null=True)),
                ("serial_number", models.CharField(blank=True, max_length=100, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("on_hand", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("reserved", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("location", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.location")),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.product")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.tenant")),
            ],
            options={
                "unique_together": {("tenant", "product", "location", "lot_code", "serial_number", "expiry_date")},
            },
        ),
        migrations.CreateModel(
            name="InventoryReservation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("qty", models.DecimalField(decimal_places=2, max_digits=12)),
                ("status", models.CharField(choices=[("ACTIVE", "Active"), ("RELEASED", "Released"), ("CONSUMED", "Consumed")], default="ACTIVE", max_length=20)),
                ("lot_code", models.CharField(blank=True, max_length=50, null=True)),
                ("serial_number", models.CharField(blank=True, max_length=100, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("ref_type", models.CharField(max_length=50)),
                ("ref_id", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("location", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.location")),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.product")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.tenant")),
            ],
        ),
        migrations.AddIndex(
            model_name="inventoryreservation",
            index=models.Index(fields=["tenant", "product", "location", "status"], name="core_invent_tenant__6b2f1f_idx"),
        ),
        migrations.AddIndex(
            model_name="inventoryreservation",
            index=models.Index(fields=["tenant", "ref_type", "ref_id"], name="core_invent_tenant__bf5df1_idx"),
        ),
        migrations.CreateModel(
            name="CycleCount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("count_date", models.DateField(default=django.utils.timezone.now)),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("SUBMITTED", "Submitted"), ("APPROVED", "Approved"), ("POSTED", "Posted")], default="DRAFT", max_length=20)),
                ("notes", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("location", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.location")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.tenant")),
            ],
        ),
        migrations.CreateModel(
            name="CycleCountLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("lot_code", models.CharField(blank=True, max_length=50, null=True)),
                ("serial_number", models.CharField(blank=True, max_length=100, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("system_qty", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("counted_qty", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("variance_qty", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("cycle_count", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="core.cyclecount")),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.product")),
            ],
            options={
                "unique_together": {("cycle_count", "product", "lot_code", "serial_number", "expiry_date")},
            },
        ),
    ]
