# Generated by Django 5.2.11 on 2026-06-03 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_reclassify_cogs_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxcode',
            name='kind',
            field=models.CharField(choices=[('STANDARD', 'Standard rate'), ('REDUCED', 'Reduced rate'), ('ZERO', 'Zero rate'), ('EXEMPT', 'Exempt'), ('OUTSIDE', 'Outside the scope of VAT')], default='STANDARD', max_length=10),
        ),
    ]
