# Generated by Django 5.2.11 on 2026-06-04 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_supplierpricehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustment',
            name='credit_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_returns', to='core.creditnote'),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_returns', to='core.supplier'),
        ),
    ]
