# Generated by Django 5.2.15 on 2026-06-10 13:02

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_returnline_final_disposition_returnline_resolved_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplenishmentPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_stock', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('max_stock', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('safety_stock', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('reorder_point', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('reorder_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('eoq', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lead_time_days', models.PositiveSmallIntegerField(default=0)),
                ('moq', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('pack_size', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replenishment_policies', to='core.location')),
                ('preferred_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replenishment_policies', to='core.supplier')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replenishment_policies', to='core.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replenishment_policies', to='core.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'product', 'location')},
            },
        ),
    ]
